
# Library `numpy` - scientific computing Python package

See http://www.numpy.org

In [1]:
import numpy  as np
import pandas as pd

In [26]:
iris = pd.read_csv("iris.csv")
iris.head(3)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [7]:
iris_ind = np.array(iris[['petal_length','petal_width','sepal_length','sepal_width']])

In [8]:
iris_ind.shape

(150, 4)

### Retrieve rows of the `iris` dataframe as Numpy arrays

In [18]:
iris_row0 = iris_ind[0]
iris_row1 = iris_ind[1]
print("Row 0: ", iris_row0)
print("Row 1: ", iris_row1)

Row 0:  [ 1.4  0.2  5.1  3.5]
Row 1:  [ 1.4  0.2  4.9  3. ]


Numpy arrays can be multiplied by a number (scalar):

In [19]:
2*iris_row0

array([  2.8,   0.4,  10.2,   7. ])

Numpy arrays can be added together, if they have the same length:

In [20]:
iris_row0 + iris_row1

array([  2.8,   0.4,  10. ,   6.5])

The `len` function returns what you expect it to.

In [39]:
len(iris_row0), len(iris_row1)

(4, 4)

Matrix multiplication is important. The `dot` Numpy function performs matrix multiplication.

In [23]:
np.dot(np.array([1,2,3]), 
       np.array([4,5,6]))

32

### Retrieve columns of a dataframe, as Numpy arrays

In [33]:
iris_petal_length = np.array(iris['petal_length'])
iris_petal_length

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  1.5,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.4,  1.3,  1.5,  1.3,  1.3,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5,  3.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  4.6,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  5.5,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  6.4,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  5.6,  5.1,  5.1,
        5.9,  5.7,  5.2,  5. ,  5.2,  5.4,  5.1])

There are several statistics function that the Numpy library provides and which can be applied to Numpy arrays. 

In [42]:
print("Mean of petal_length"    , np.mean(iris_petal_length))
print("Variance of petal_length", np.var(iris_petal_length))

Mean of petal_length 3.758
Variance of petal_length 3.09550266667
